"""scope3track — Carbon and Scope 3 emissions tracking for SMBs and enterprise supply chains."""
from scope3track.models import (
    EmissionEntry,
    EmissionReport,
    EmissionScope,
    EmissionUnit,
    Scope3Category,
    SupplierEmissions,
)
from scope3track.calculator import (
    EmissionCalculator,
    EmissionFactorRegistry,
    default_registry,
)
from scope3track.exceptions import (
    CalculationError,
    ReportError,
    Scope3TrackError,
    ValidationError,
)
from scope3track.advanced import (
    AuditLog,
    CancellationToken,
    CarbonReductionScenarioModeller,
    EmissionCache,
    EmissionDiff,
    EmissionDriftDetector,
    EmissionHotspot,
    EmissionHotspotAnalyzer,
    EmissionPipeline,
    EmissionProfiler,
    EmissionReportExporter,
    EmissionRule,
    EmissionSpanEmitter,
    EmissionValidator,
    NetZeroMilestone,
    NetZeroRoadmap,
    NetZeroRoadmapGenerator,
    PIIScrubber,
    RateLimiter,
    ReductionScenario,
    SBTiAlignmentChecker,
    SBTiAlignmentResult,
    ScenarioModelResult,
    SupplierEmissionRanker,
    SupplierRank,
    abatch_calculate,
    batch_calculate,
    diff_entries,
    entries_to_ndjson,
    stream_entries,
)

__version__ = "1.2.0"
__all__ = [
    # Core
    "EmissionCalculator",
    "EmissionFactorRegistry",
    "default_registry",
    "EmissionEntry",
    "EmissionReport",
    "EmissionScope",
    "EmissionUnit",
    "Scope3Category",
    "SupplierEmissions",
    # Exceptions
    "Scope3TrackError",
    "CalculationError",
    "ValidationError",
    "ReportError",
    # Advanced — base
    "EmissionCache",
    "EmissionPipeline",
    "EmissionValidator",
    "EmissionRule",
    "RateLimiter",
    "CancellationToken",
    "batch_calculate",
    "abatch_calculate",
    "EmissionProfiler",
    "EmissionDriftDetector",
    "EmissionReportExporter",
    "stream_entries",
    "entries_to_ndjson",
    "EmissionDiff",
    "diff_entries",
    "AuditLog",
    "PIIScrubber",
    # Advanced — expert v1.1.0
    "SBTiAlignmentChecker",
    "SBTiAlignmentResult",
    "SupplierEmissionRanker",
    "SupplierRank",
    "CarbonReductionScenarioModeller",
    "ReductionScenario",
    "ScenarioModelResult",
    "EmissionSpanEmitter",
    # Advanced — expert v1.2.0
    "EmissionHotspotAnalyzer",
    "EmissionHotspot",
    "NetZeroRoadmapGenerator",
    "NetZeroRoadmap",
    "NetZeroMilestone",
]
